import json

data = {
  "nodes": [
    {"id":"flutter-billing-app","label":"Flutter Billing App","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/CLAUDE.md","confidence":0.95},
    {"id":"flutter-framework","label":"Flutter 3.x (Dart)","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/CLAUDE.md","confidence":0.95},
    {"id":"flutter-bloc","label":"flutter_bloc (BLoC)","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/CLAUDE.md","confidence":0.95},
    {"id":"supabase-cloud-db","label":"Supabase (PostgreSQL + Realtime)","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/CLAUDE.md","confidence":0.95},
    {"id":"hive-cache","label":"Hive (Local Cache)","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/CLAUDE.md","confidence":0.95},
    {"id":"supabase-auth","label":"Supabase Auth","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/CLAUDE.md","confidence":0.95},
    {"id":"go-router","label":"go_router (Navigation)","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/CLAUDE.md","confidence":0.95},
    {"id":"get-it-di","label":"get_it (DI)","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/CLAUDE.md","confidence":0.95},
    {"id":"print-bluetooth-thermal","label":"print_bluetooth_thermal (ESC/POS)","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/CLAUDE.md","confidence":0.95},
    {"id":"mobile-scanner","label":"mobile_scanner (Barcode + QR)","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/CLAUDE.md","confidence":0.95},
    {"id":"pretty-qr-code","label":"pretty_qr_code (QR Gen)","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/CLAUDE.md","confidence":0.95},
    {"id":"clean-architecture","label":"Clean Architecture (Presentation/Domain/Data)","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/CLAUDE.md","confidence":0.95},
    {"id":"update-rule","label":"CRITICAL Update Rule (memory.md + graphify + md files)","type":"rule","source_file":"D:/Projects/flutter_billing_app-main/CLAUDE.md","confidence":0.9},
    {"id":"autopilot-mode","label":"Auto-Pilot Mode (no questions, just execute)","type":"rule","source_file":"D:/Projects/flutter_billing_app-main/CLAUDE.md","confidence":0.9},
    {"id":"parallel-work-rule","label":"Parallel Work Rule (multiple subagents)","type":"rule","source_file":"D:/Projects/flutter_billing_app-main/CLAUDE.md","confidence":0.9},
    {"id":"supabase-migration-rule","label":"Supabase Migration Rule (always migration file)","type":"rule","source_file":"D:/Projects/flutter_billing_app-main/CLAUDE.md","confidence":0.9},
    {"id":"dart-only-fix-preference","label":"Dart-Only Fix Preference (avoid SQL migrations)","type":"rule","source_file":"D:/Projects/flutter_billing_app-main/CLAUDE.md","confidence":0.92},
    {"id":"herder-cli","label":"Herder CLI (live pane monitoring w5:p8)","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/CLAUDE.md","confidence":0.9},
    {"id":"graphify-skill","label":"graphify knowledge graph skill","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/CLAUDE.md","confidence":0.9},
    {"id":"design-system","label":"Design System (Material 3)","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/design.md","confidence":0.95},
    {"id":"theme-primary-color","label":"Primary Color #6C63FF","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/design.md","confidence":0.9},
    {"id":"theme-secondary-color","label":"Secondary Color #03DAC6","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/design.md","confidence":0.9},
    {"id":"typography-ibm-plex","label":"Typography IBM Plex Sans","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/design.md","confidence":0.9},
    {"id":"component-primarybutton","label":"PrimaryButton Component","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/design.md","confidence":0.85},
    {"id":"component-statcard","label":"StatCard Widget","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/design.md","confidence":0.85},
    {"id":"component-dashboardactioncard","label":"DashboardActionCard + QuickActionTile","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/design.md","confidence":0.85},
    {"id":"screen-dashboard","label":"Dashboard Screen (/)","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/design.md","confidence":0.9},
    {"id":"screen-scanner","label":"Scanner Screen (/scan)","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/design.md","confidence":0.9},
    {"id":"screen-checkout","label":"Checkout Screen (/scan/checkout)","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/design.md","confidence":0.9},
    {"id":"multi-tenant-shop-isolation","label":"Multi-Tenant Shop Data Isolation","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/memory.md","confidence":0.95},
    {"id":"shop-id-column","label":"shop_id column (UUID FK to shops)","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/memory.md","confidence":0.92},
    {"id":"rls-shop-scoping","label":"RLS belongs_to_shop() scoping","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/memory.md","confidence":0.92},
    {"id":"migration-004-shop-scoping","label":"Migration 004_shop_data_scoping.sql","type":"document","source_file":"D:/Projects/flutter_billing_app-main/memory.md","confidence":0.9},
    {"id":"shop-id-dart-threading","label":"shop_id Dart threading (repositories/blocs)","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/memory.md","confidence":0.9},
    {"id":"email-verification-gate","label":"Email Verification Gate (Dart-only)","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/memory.md","confidence":0.9},
    {"id":"report-feature","label":"Reports & History Feature","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/memory.md","confidence":0.9},
    {"id":"supabase-realtime-sync","label":"Supabase Realtime Sync (products)","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/memory.md","confidence":0.9},
    {"id":"auth-feature","label":"Auth Feature (Supabase + Google OAuth)","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/memory.md","confidence":0.9},
    {"id":"category-feature","label":"Category Feature (CRUD)","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/memory.md","confidence":0.9},
    {"id":"stock-validation","label":"Stock Validation Before Bill","type":"concept","source_file":"D:/Projects/flutter_billing_app-main/memory.md","confidence":0.9}
  ],
  "edges": [
    {"source":"flutter-billing-app","target":"flutter-framework","label":"uses","confidence":0.95},
    {"source":"flutter-billing-app","target":"flutter-bloc","label":"uses","confidence":0.95},
    {"source":"flutter-billing-app","target":"supabase-cloud-db","label":"uses","confidence":0.95},
    {"source":"flutter-billing-app","target":"hive-cache","label":"uses","confidence":0.95},
    {"source":"flutter-billing-app","target":"supabase-auth","label":"uses","confidence":0.95},
    {"source":"flutter-billing-app","target":"go-router","label":"uses","confidence":0.95},
    {"source":"flutter-billing-app","target":"get-it-di","label":"uses","confidence":0.95},
    {"source":"flutter-billing-app","target":"print-bluetooth-thermal","label":"uses","confidence":0.95},
    {"source":"flutter-billing-app","target":"mobile-scanner","label":"uses","confidence":0.95},
    {"source":"flutter-billing-app","target":"pretty-qr-code","label":"uses","confidence":0.95},
    {"source":"flutter-billing-app","target":"clean-architecture","label":"describes","confidence":0.95},
    {"source":"clean-architecture","target":"flutter-bloc","label":"relates_to","confidence":0.9},
    {"source":"flutter-billing-app","target":"update-rule","label":"governed_by","confidence":0.9},
    {"source":"flutter-billing-app","target":"autopilot-mode","label":"governed_by","confidence":0.9},
    {"source":"flutter-billing-app","target":"parallel-work-rule","label":"governed_by","confidence":0.9},
    {"source":"flutter-billing-app","target":"supabase-migration-rule","label":"governed_by","confidence":0.9},
    {"source":"flutter-billing-app","target":"dart-only-fix-preference","label":"governed_by","confidence":0.92},
    {"source":"flutter-billing-app","target":"herder-cli","label":"uses","confidence":0.85},
    {"source":"flutter-billing-app","target":"graphify-skill","label":"uses","confidence":0.9},
    {"source":"update-rule","target":"graphify-skill","label":"relates_to","confidence":0.9},
    {"source":"dart-only-fix-preference","target":"supabase-migration-rule","label":"qualifies","confidence":0.85},
    {"source":"design-system","target":"flutter-framework","label":"describes","confidence":0.9},
    {"source":"design-system","target":"theme-primary-color","label":"describes","confidence":0.9},
    {"source":"design-system","target":"theme-secondary-color","label":"describes","confidence":0.9},
    {"source":"design-system","target":"typography-ibm-plex","label":"describes","confidence":0.9},
    {"source":"design-system","target":"component-primarybutton","label":"describes","confidence":0.85},
    {"source":"design-system","target":"component-statcard","label":"describes","confidence":0.85},
    {"source":"design-system","target":"component-dashboardactioncard","label":"describes","confidence":0.85},
    {"source":"design-system","target":"screen-dashboard","label":"describes","confidence":0.9},
    {"source":"design-system","target":"screen-scanner","label":"describes","confidence":0.9},
    {"source":"design-system","target":"screen-checkout","label":"describes","confidence":0.9},
    {"source":"screen-dashboard","target":"component-statcard","label":"uses","confidence":0.85},
    {"source":"screen-dashboard","target":"component-dashboardactioncard","label":"uses","confidence":0.85},
    {"source":"multi-tenant-shop-isolation","target":"shop-id-column","label":"implemented_by","confidence":0.92},
    {"source":"multi-tenant-shop-isolation","target":"rls-shop-scoping","label":"implemented_by","confidence":0.92},
    {"source":"multi-tenant-shop-isolation","target":"migration-004-shop-scoping","label":"implemented_by","confidence":0.9},
    {"source":"multi-tenant-shop-isolation","target":"shop-id-dart-threading","label":"implemented_by","confidence":0.9},
    {"source":"shop-id-column","target":"supabase-cloud-db","label":"lives_in","confidence":0.9},
    {"source":"rls-shop-scoping","target":"supabase-cloud-db","label":"lives_in","confidence":0.9},
    {"source":"migration-004-shop-scoping","target":"supabase-cloud-db","label":"applies_to","confidence":0.9},
    {"source":"shop-id-dart-threading","target":"flutter-bloc","label":"relates_to","confidence":0.85},
    {"source":"multi-tenant-shop-isolation","target":"dart-only-fix-preference","label":"exception_to","confidence":0.88},
    {"source":"email-verification-gate","target":"dart-only-fix-preference","label":"follows","confidence":0.88},
    {"source":"email-verification-gate","target":"auth-feature","label":"part_of","confidence":0.85},
    {"source":"shop-id-dart-threading","target":"auth-feature","label":"relates_to","confidence":0.8},
    {"source":"report-feature","target":"supabase-cloud-db","label":"uses","confidence":0.9},
    {"source":"report-feature","target":"flutter-bloc","label":"uses","confidence":0.9},
    {"source":"report-feature","target":"component-statcard","label":"uses","confidence":0.85},
    {"source":"supabase-realtime-sync","target":"supabase-cloud-db","label":"uses","confidence":0.9},
    {"source":"supabase-realtime-sync","target":"flutter-bloc","label":"uses","confidence":0.85},
    {"source":"auth-feature","target":"supabase-auth","label":"uses","confidence":0.9},
    {"source":"category-feature","target":"supabase-cloud-db","label":"uses","confidence":0.9},
    {"source":"category-feature","target":"flutter-bloc","label":"uses","confidence":0.9},
    {"source":"stock-validation","target":"supabase-cloud-db","label":"uses","confidence":0.85},
    {"source":"stock-validation","target":"flutter-bloc","label":"uses","confidence":0.85},
    {"source":"stock-validation","target":"dart-only-fix-preference","label":"follows","confidence":0.85},
    {"source":"auth-feature","target":"flutter-billing-app","label":"part_of","confidence":0.9},
    {"source":"category-feature","target":"flutter-billing-app","label":"part_of","confidence":0.9},
    {"source":"report-feature","target":"flutter-billing-app","label":"part_of","confidence":0.9},
    {"source":"supabase-realtime-sync","target":"flutter-billing-app","label":"part_of","confidence":0.85},
    {"source":"stock-validation","target":"flutter-billing-app","label":"part_of","confidence":0.85}
  ],
  "hyperedges": [],
  "input_tokens": 0,
  "output_tokens": 0
}

with open("D:/Projects/flutter_billing_app-main/graphify-out/.graphify_chunk_01.json", "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("nodes:", len(data["nodes"]))
print("edges:", len(data["edges"]))
